### ISSUE TITLE
Proposal: show all possible issues

### ISSUE THREAD

**Issue by RyanSiu1995** [rrrene/credo#633]
I am working on the development plugin with credo. That plugin requires to map all credo possible issues into a particular format. 
Therefore, I need to export the all current possible issues into json format. Any ideas on how I can export this kinds of information? Or it is a new feature for credo?
Thank you!

**Comment by rrrene** [comment]
> Any ideas on how I can export this kinds of information?

@RyanSiu1995 `mix credo info --verbose` lists all checks (among other things) that will be part of the analysis:

```
System:
  Credo: 1.0.1
  Elixir: 1.8.0
  Erlang: 21
Configuration:
  Checks:
    - Elixir.Credo.Check.Consistency.ExceptionNames
    - Elixir.Credo.Check.Consistency.LineEndings
    - Elixir.Credo.Check.Consistency.ParameterPatternMatching
    - Elixir.Credo.Check.Consistency.SpaceAroundOperators
    - Elixir.Credo.Check.Consistency.SpaceInParentheses
[... you get the idea ...]
```

You can get the output in JSON format by adding `--format=json`
